version: "3"

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - user_profiles

  kafka:
    image: 'bitnami/kafka:latest'
    user: root
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./Kafka:/bitnami/kafka
    networks:
      - user_profiles
    depends_on:
      - zookeeper

  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042
    networks:
      - cassandra
    hostname: "cassandra"

  docker-cqlsh:
    image: nuvo/docker-cqlsh
    networks:
      - cassandra
    environment:
      - CQLSH_HOST=cassandra
      - CQLSH_PORT=9042
      - CQLVERSION=3.4.6
    command: ["tail", "-f", "/dev/null"]
  
networks:
  user_profiles:
  cassandra:
    external: true